apiVersion: v1
kind: Namespace
metadata:
  name: redicloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: redicloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: redicloud/website
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: redicloud
spec:
  selector:
    app: website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP